### PR TITLE
Move to broth 2.2.0

### PR DESCRIPTION
**Pull request by silviapfeiffer**
Fixes most of issue #61 

There is still a problem with bufferutil@1.1.0 - tracking that down now...

### CODE REVIEW

**Comment by DamonOehlman** [comment]
Hey Silvia - thanks for this.  I'm over in Cambodia at the moment, so if @nathanoehlman could eyeball any rtc.io PRs and merge them that would be awesome.  If there is anything that is in one of my own repos then I'll try to get to it as soon as I can.

**Comment by nathanoehlman** [comment]
Looks good @silviapfeiffer :)

**Comment by silviapfeiffer** [comment]
Thanks! At least the tests passed here. :-)

**Comment by silviapfeiffer** [comment]
Probably need to release a new version, btw.

**Comment by nathanoehlman** [comment]
Yeah - I will do, just once I've taken a bit more of a look at the `bufferutil` stuff. Looks like it's an issue in the later versions of node (>= 4), and is caused by combinations of npm and GCC.

**Comment by silviapfeiffer** [comment]
Yes, and do look at https://github.com/DamonOehlman/messenger-ws/pull/2, which should help address the bufferutil stuff.

**Pull request merged**
