### PR TITLE
Added option if the user wants to rely on their switchboard to tell if the call is still going

### PR DESCRIPTION
**Pull request by magestican**

### CODE REVIEW

**Comment by silviapfeiffer** [comment]
Curious: How do you tell a disconnection when ignoring the heartbeat?

**Comment by magestican** [comment]
The socket.io server we use has a peer.on('disconnected') event, when this happens we remove the participant from the room and inform the client to remove the video tile.

The event call:expired in its current state doesnt really help as it forces the whole connection initialization to happen again between all peers. 

I dont really know whats wrong with the current implementation of the method, I could assume that relying on the client side Date object to be accurate can be an issue. it would be more reliable to count miliseconds between the last response of a heartbeat or even using a timeout to add seconds.

My fast solution to this was to add an option to tell quickconnect all heartbeats go fine.

**Comment by markjrodrigues** [comment]
I think setting the delay to 0 will have the same effect as start() will not kick off the timer

**Comment by magestican** [comment]
@markjrodrigues  apparently something else triggers the heartbeat status check on certain circumstances even if we pass 0

**Comment by warrenjmcdonald** [comment]
@silviapfeiffer This most relevant aspect of this change is that the underlying socket.io transport already implements connection monitoring scheme, so the higher level one rtc.io one is unnecessarily duplicating  this. 
We have tested thoroughly and recommend this option for those that want to use socket.io transport layer.

**Comment by nathanoehlman** [comment]
Hi all,

Being able to turn off the heartbeat is definitely something that needs to be fixed. As Bryan indicated, passing `0` to the heartbeat parameter is broken. I'm wondering whether simply fixing this so heartbeats aren't sent would work for your use case, as opposed to adding a new option?

I can see a potential for `ignoreDisconnection` however, where you may want heartbeat messages to continue to be sent in order to keep the websocket connection alive, but not wanting any disconnections to trigger the `call:expired` event, but given socket.io already has inbuilt ping/pong messages, I imagine this isn't the case.

I'm happy to merge this in if it's the latter. At any rate, I'll fix the heartbeat parameter now.

Cheers,
Nathan

**Comment by magestican** [comment]
Merging this PR which adds a new option that clearly specifies what it does would be less obscure than passing 0 as the heartbeat, at least for us, so it would be nice if you merge it, its also good if the 0 value of the heartbeat option is fixed as well.

**Comment by markjrodrigues** [comment]
Thanks @nathanoehlman.

I have a folk I have been playing with which may have 2 more changes worth considering (https://github.com/markjrodrigues/rtc-quickconnect/commit/5519ab67055543b6366c8d0682e143c9012e052c)

Line 14:
var lastping = new Date(0);

Line 61:
if (timer) {
        clearInterval(timer);
        timer = null;
}


The other changes were not as interesting.
I haven't signed the appropriate paperwork to contribute yet but if you feel these 2 changes are worthwhile can you also please make them?

Thanks

**Comment by nathanoehlman** [comment]
No problems - merged in and published as `5.6.0`

**Comment by nathanoehlman** [comment]
Hi @markjrodrigues 

Definitely will pull in the setting the timer to null - thanks.

I'm not sure why about the `var lastping = new Date(0);` change though. `lastping` is being used to contain and compare against integer timestamps (ie. `Date.now()`) so setting it to a `Date` object - while it will still evaluate correctly - seems superfluous. Happy to be proven wrong though.

Cheers,
Nathan

**Comment by markjrodrigues** [comment]
Wasn't sure what int <= Datetime would evaluate to first time through (although I am sure there is a known rule for it).
Once it has been set then it is a straight Datetime <= Datetime comparison which is predictable.
My understanding is that Datetime(0) would result in a Datetime of 1/1/1970 which is then consistent with the other processing.

I am no JS guru so happy to leave to your discretion.

Thanks for the quick turnaround on the changes!

**Comment by nathanoehlman** [comment]
@markjrodrigues I see where the confusion may lie - the comparisons are actually currently int <= int. `Date.now()` returns the number of milliseconds since 1/1/1970 - the equivalent of `(new Date()).getTime()` as opposed to an instance of `Date`.

Adding in the `lastping = new Date(0)` actually changes it to a Datetime <= int comparison, so I'll leave it as it currently is.

And no problem with the turnaround - happy to be of assistance.

Cheers,
Nathan

**Comment by markjrodrigues** [comment]
Cool. Makes sense (and I have learned something new about JS which is a bonus) :smile:

**Pull request merged**
